theme = "the-new-dynamic-hugo-base"
DefaultContentLanguage = "en"
languageCode = "en-us"
baseurl = "/"

description = "A Program we’ve develop to support English-langauge publishers based outside the U.S. to obtain marketing support across your entire list. "
author = "Bud Parr"
copyright = "Copyright (c) 2008 - 2014, Bud Parr; all rights reserved."
canonifyurls = true
paginate = 3

title = "Cursor"
weight = 1


[params]

  hero_copy = "Think Cursor"
